### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by johanngonzalez** [reyhoun/acf-typography#4]
Really nice plugin! I've already activated the plugin and selected some options. However, I can't find anywhere in the documentation how to print these fields.

I've tried to figure it out by opening the plugin file without luck.

For example:

<?php get_field('font-weight','options'); ?>

Any ideas?

**Comment by parhumm** [comment]
Hi! I'm happy you like our plugin.
We use this plugin with an other plugin called [Sass Watcher](https://github.com/reyhoun/sass-watcher) to use fields directly in our Sass codes(CSS).

But you can use it in your php code like this:

```
// Use 'options' if your field is on Option Page
$my_typo_field = get_field( 'YOUR_FIELD_NAME', 'options' );

// Don't send second parameter if your field use in post types, like this:
// $my_typo_field = get_field( 'YOUR_FIELD_NAME' );

// Now print your field array to see all subfields:
echo '<pre>';
print_r($my_typo_field);
echo '</pre>';

// You see something like this:
// Array
// (
//     [font-family] => Open Sans
//     [font-weight] => 400
//     [backupfont] => Arial, Helvetica, sans-serif
//     [text_align] => left
//     [direction] => ltr
//     [font_style] => normal
//     [font_size] => 20
//     [line_height] => 25
//     [letter_spacing] => 0
//     [text-color] => #000000
// )

// Now you can use array like this(get 'font-weight'):
echo $my_typo_field['font-weight'];
```

Maybe this #3 issue was helpful for you.
